version: '3'
services:
  node-express-api:
    build:
      context: ./node-express-api
    ports:
      - "3001:3001"

  vite-react-frontend:
    build:
      context: ./vite-react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - node-express-api